### PR TITLE
Change static asserts with iterator traits

### LINKED ISSUE #60: Iterator traits checking causes compilation errors
During compilation with gcc 6.2.1. I get:
```shell
$ make
Scanning dependencies of target tilegen
[  1%] Building CXX object Wangscape/tilegen/CMakeFiles/tilegen.dir/partition/TilePartitionerPerlin.cpp.o
In file included from /home/hryniuk/projekty/Wangscape/Wangscape/noise/ModuleManager.h:8:0,
                 from /home/hryniuk/projekty/Wangscape/Wangscape/tilegen/partition/TilePartitionerPerlin.h:6,
                 from /home/hryniuk/projekty/Wangscape/Wangscape/tilegen/partition/TilePartitionerPerlin.cpp:1:
/home/hryniuk/projekty/Wangscape/Wangscape/noise/Reseedable.h: In member function ‘noise::Reseedable noise::Reseedable::terrace(InputIt, InputIt, bool)’:
/home/hryniuk/projekty/Wangscape/Wangscape/noise/Reseedable.h:62:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class, class> struct std::is_same’
                   std::input_iterator_tag>::value,
                                          ^
/home/hryniuk/projekty/Wangscape/Wangscape/noise/Reseedable.h:62:42: note:   expected a type, got ‘typename std::iterator_traits<_Iter>::iterator_category:: input_iterator_tag’
/home/hryniuk/projekty/Wangscape/Wangscape/noise/Reseedable.h: In member function ‘noise::Reseedable noise::Reseedable::curve(InputIt, InputIt)’:
/home/hryniuk/projekty/Wangscape/Wangscape/noise/Reseedable.h:80:55: error: type/value mismatch at argument 1 in template parameter list for ‘template<class, class> struct std::is_same’
                                std::input_iterator_tag>::value,
                                                       ^
/home/hryniuk/projekty/Wangscape/Wangscape/noise/Reseedable.h:80:55: note:   expected a type, got ‘typename std::iterator_traits<_Iter>::iterator_category:: input_iterator_tag’
make[2]: *** [Wangscape/tilegen/CMakeFiles/tilegen.dir/build.make:231: Wangscape/tilegen/CMakeFiles/tilegen.dir/partition/TilePartitionerPerlin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:578: Wangscape/tilegen/CMakeFiles/tilegen.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

If I see correctly that's because of redundant `::input_iterator_tag` fragments.

### PR DESCRIPTION
**Pull request by hryniuk**
Fixes #60.

### CODE REVIEW

**Comment by hryniuk** [comment]
Check it on VS, please.

File: Wangscape/noise/Reseedable.h [hunk 1]
```diff
@@ -58,8 +58,8 @@ struct Reseedable final
 template<typename InputIt>
 inline Reseedable Reseedable::terrace(InputIt first, InputIt last, bool inverted)
 {
-    static_assert(std::is_same<std::iterator_traits<InputIt>::iterator_category::input_iterator_tag,
-                  std::input_iterator_tag>::value,
+    static_assert(std::is_same<typename std::iterator_traits<InputIt>::iterator_category,
```
Comment (serin-delaunay) [inline Wangscape/noise/Reseedable.h]: Does this still compile if you instantiate the template with an `InputIt` which is not an InputIterator, but is something more powerful, such as BidirectionalIterator? There should probably be a test to make sure the intended cases compile.

Comment (serin-delaunay) [inline Wangscape/noise/Reseedable.h]: For me this prevents `TestReseedable::TestReseedableTerraceManual` from compiling, because `std::vector::const_iterator` is not an `InputIterator`. This should be implemented with `std::is_base_of` or `std::convertible_to`.

Comment (hryniuk) [inline Wangscape/noise/Reseedable.h]: Right, I thought about it, but didn't check completely before. I'll change it to `std::is_base_of`.
