### PR TITLE
Make resolution option a vector; support odd values

### LINKED ISSUE #12: Support odd tile resolutions
At the moment various parts of the code assume the tile resolution is even. Odd resolutions have not been tested. There may be unforeseen errors or crashes when the tile resolution is odd.

The correct behaviour of #11 in particular is unclear - perhaps it should be an option in the JSON options.

### PR DESCRIPTION
**Pull request by serin-delaunay**
Resolves #12. Resolves item 1 from #32.

Update everything that uses resolution, including tile partitioners,
tile[set] generator, metaoutput, terrain image rearranger, examples.

Apart from changing the resolution option from an integer to an array of two integers, there is another important and less obvious change to the options file format: source tile offsets in images are now counted in pixels, not tiles. This doesn't affect any of the current examples, which have offset `[0,0]` for all source terrain tiles.

An eyeball test with resolution `[31, 29]` indicates terrain images are
correctly rearranged even with odd resolutions, but it's probably worth
making a real test case.

Needs matching changes in Wangview (https://github.com/Wangscape/Wangview/pull/14), which should be merged at the same time.

### CODE REVIEW

**Comment by serin-delaunay** [comment]
Rebased on master.

File: Wangscape/tilegen/partition/TilePartitionerGradient.cpp [hunk 1]
```diff
@@ -21,22 +22,22 @@ void TilePartitionerGradient::makePartition(TilePartition & regions,
...
+        for (size_t y = 0; y < mOptions.tileFormat.resolution.y; y++)
         {
-            weights[0] = static_cast<double>(gradientWeight(x, y, 0, 0, quarter_res));
-            weights[1] = static_cast<double>(gradientWeight(x, y, 0, resolution_sub_1, quarter_res));
-            weights[2] = static_cast<double>(gradientWeight(x, y, resolution_sub_1, 0, quarter_res));
-            weights[3] = static_cast<double>(gradientWeight(x, y, resolution_sub_1, resolution_sub_1, quarter_res));
+            weights[0] = static_cast<double>(gradientWeight({x, y}, {0, 0}, quarter_res));
+            weights[1] = static_cast<double>(gradientWeight({x, y}, {0, resolution_sub_1.y}, quarter_res));
+            weights[2] = static_cast<double>(gradientWeight({x, y}, {resolution_sub_1.x, 0}, quarter_res));
+            weights[3] = static_cast<double>(gradientWeight({x, y}, {resolution_sub_1.x, resolution_sub_1.y}, quarter_res));
```
Comment (serin-delaunay) [inline Wangscape/tilegen/partition/TilePartitionerGradient.cpp]: These four `weights[]` assignments produce warnings on 64-bit gcc because a `size_t` (unsigned long) is implicitly converted to an `unsigned int`.

Comment (serin-delaunay) [inline Wangscape/tilegen/partition/TilePartitionerGradient.cpp]: Fixed.

File: Wangscape/TerrainImages.cpp [hunk 2]
```diff
@@ -45,10 +46,8 @@ void TerrainImages::addTerrain(TerrainID tid, std::string image_filename, std::s
         it = source_images.insert({ filename, img }).first;
     }
     sf::Vector2i offset(offset_x, offset_y);
-    sf::Vector2i box(resolution, resolution);
-    offset *= (int)resolution;
```
Comment (hryniuk) [inline Wangscape/TerrainImages.cpp]: Why is this line removed?

Comment (serin-delaunay) [inline Wangscape/TerrainImages.cpp]: These two lines caused the source tile offset in the source image to be measured in multiples of the resolution instead of in pixels. It didn't seem like a useful restriction; eventually some users may have source images with tiles not aligned to the grid.
